"""Exact numeric/categorical column names the saved pipelines expect, in the shape
`preprocessor.transform()` was fit on (Modeling/home_credit_default_risk.ipynb, `col-types` cell).
Columns not covered by the API's request schema are left NaN and filled in by the
pipeline's own fitted SimpleImputer (median for numeric, most-frequent for categorical).
"""

NUM_COLS = [
    'Children', 'Income', 'Credit Amount', 'Annuity', 'Goods Price',
    'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_REGISTRATION',
    'DAYS_ID_PUBLISH', 'OWN_CAR_AGE', 'FLAG_MOBIL', 'FLAG_EMP_PHONE', 'FLAG_WORK_PHONE',
    'FLAG_CONT_MOBILE', 'FLAG_PHONE', 'FLAG_EMAIL', 'Family Members',
    'REGION_RATING_CLIENT', 'REGION_RATING_CLIENT_W_CITY', 'HOUR_APPR_PROCESS_START',
    'REG_REGION_NOT_LIVE_REGION', 'REG_REGION_NOT_WORK_REGION', 'LIVE_REGION_NOT_WORK_REGION',
    'REG_CITY_NOT_LIVE_CITY', 'REG_CITY_NOT_WORK_CITY', 'LIVE_CITY_NOT_WORK_CITY',
    'External Score 1', 'External Score 2', 'External Score 3',
    'APARTMENTS_AVG', 'BASEMENTAREA_AVG', 'YEARS_BEGINEXPLUATATION_AVG', 'YEARS_BUILD_AVG',
    'COMMONAREA_AVG', 'ELEVATORS_AVG', 'ENTRANCES_AVG', 'FLOORSMAX_AVG', 'FLOORSMIN_AVG',
    'LANDAREA_AVG', 'LIVINGAPARTMENTS_AVG', 'LIVINGAREA_AVG', 'NONLIVINGAPARTMENTS_AVG',
    'NONLIVINGAREA_AVG', 'APARTMENTS_MODE', 'BASEMENTAREA_MODE', 'YEARS_BEGINEXPLUATATION_MODE',
    'YEARS_BUILD_MODE', 'COMMONAREA_MODE', 'ELEVATORS_MODE', 'ENTRANCES_MODE', 'FLOORSMAX_MODE',
    'FLOORSMIN_MODE', 'LANDAREA_MODE', 'LIVINGAPARTMENTS_MODE', 'LIVINGAREA_MODE',
    'NONLIVINGAPARTMENTS_MODE', 'NONLIVINGAREA_MODE', 'APARTMENTS_MEDI', 'BASEMENTAREA_MEDI',
    'YEARS_BEGINEXPLUATATION_MEDI', 'YEARS_BUILD_MEDI', 'COMMONAREA_MEDI', 'ELEVATORS_MEDI',
    'ENTRANCES_MEDI', 'FLOORSMAX_MEDI', 'FLOORSMIN_MEDI', 'LANDAREA_MEDI',
    'LIVINGAPARTMENTS_MEDI', 'LIVINGAREA_MEDI', 'NONLIVINGAPARTMENTS_MEDI', 'NONLIVINGAREA_MEDI',
    'TOTALAREA_MODE', 'OBS_30_CNT_SOCIAL_CIRCLE', 'DEF_30_CNT_SOCIAL_CIRCLE',
    'OBS_60_CNT_SOCIAL_CIRCLE', 'DEF_60_CNT_SOCIAL_CIRCLE', 'DAYS_LAST_PHONE_CHANGE',
    'FLAG_DOCUMENT_2', 'FLAG_DOCUMENT_3', 'FLAG_DOCUMENT_4', 'FLAG_DOCUMENT_5',
    'FLAG_DOCUMENT_6', 'FLAG_DOCUMENT_7', 'FLAG_DOCUMENT_8', 'FLAG_DOCUMENT_9',
    'FLAG_DOCUMENT_10', 'FLAG_DOCUMENT_11', 'FLAG_DOCUMENT_12', 'FLAG_DOCUMENT_13',
    'FLAG_DOCUMENT_14', 'FLAG_DOCUMENT_15', 'FLAG_DOCUMENT_16', 'FLAG_DOCUMENT_17',
    'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20', 'FLAG_DOCUMENT_21',
    'AMT_REQ_CREDIT_BUREAU_HOUR', 'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
    'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT', 'AMT_REQ_CREDIT_BUREAU_YEAR',
    'Age', 'Years Employed',
    'BUREAU_LOAN_COUNT', 'BUREAU_ACTIVE_RATIO', 'BUREAU_DAYS_CREDIT_MEAN',
    'BUREAU_CREDIT_SUM_MEAN', 'BUREAU_CREDIT_SUM_DEBT_MEAN', 'BUREAU_CREDIT_OVERDUE_MEAN',
    'BUREAU_DPD_STATUS_RATE_MEAN', 'BUREAU_CREDIT_MAX_OVERDUE_MEAN', 'BUREAU_CNT_PROLONGED_SUM',
    'BUREAU_DAYS_CREDIT_ENDDATE_MEAN', 'BUREAU_CREDIT_SUM_LIMIT_MEAN', 'BUREAU_DEBT_TO_CREDIT_MEAN',
    'BUREAU_CREDIT_TYPE_NUNIQUE',
    'PREV_APP_COUNT', 'PREV_REFUSAL_RATE', 'PREV_APPROVAL_RATE', 'PREV_AMT_CREDIT_MEAN',
    'PREV_AMT_ANNUITY_MEAN', 'PREV_DAYS_DECISION_MEAN', 'PREV_CNT_PAYMENT_MEAN',
    'PREV_DOWN_PAYMENT_RATE_MEAN', 'PREV_APP_CREDIT_RATIO_MEAN', 'PREV_INSURED_RATE',
    'POS_RECORD_COUNT', 'POS_SK_DPD_MEAN', 'POS_SK_DPD_DEF_MEAN', 'POS_COMPLETED_RATIO',
    'POS_CNT_INSTALMENT_MEAN', 'POS_MONTHS_BALANCE_MIN',
    'CC_RECORD_COUNT', 'CC_UTILIZATION_MEAN', 'CC_SK_DPD_MEAN', 'CC_DRAWINGS_ATM_MEAN',
    'CC_CNT_DRAWINGS_MEAN', 'CC_PAYMENT_TO_MIN_MEAN',
    'INSTALLMENT_COUNT', 'INSTALLMENT_LATE_DAYS_MEAN', 'INSTALLMENT_PAYMENT_DIFF_MEAN',
    'INSTALLMENT_LATE_RATE', 'INSTALLMENT_UNDERPAID_RATE', 'INSTALLMENT_NUM_VERSION_NUNIQUE',
]

CAT_COLS = [
    'Contract Type', 'Gender', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'NAME_TYPE_SUITE',
    'Income Type', 'Education', 'Family Status', 'Housing Type', 'Occupation',
    'WEEKDAY_APPR_PROCESS_START', 'Organization Type', 'FONDKAPREMONT_MODE',
    'HOUSETYPE_MODE', 'WALLSMATERIAL_MODE', 'EMERGENCYSTATE_MODE',
]

ALL_COLS = NUM_COLS + CAT_COLS


def prettify_feature_name(raw_name: str) -> str:
    """'cat__Education_Higher education' -> 'Education = Higher education'; numeric
    columns pass through unchanged (ColumnTransformer prefixes them 'num__<col>')."""
    name = raw_name.split("__", 1)[-1]
    for col in CAT_COLS:
        if name.startswith(col + "_"):
            category = name[len(col) + 1:]
            return f"{col} = {category}"
    return name
